name: moo
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  failed:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - if: ${{ success() || failure() }}
        uses: actions/cache@v3
        id: cache
        with:
          path: hello
          key: hello-${{ github.job }}
      - run: exit 1
      - if: ${{ success() || failure() }}
        run: |
          mkdir -vp hello/
          echo "Hello World!" > greetings.txt

  successful:
    needs: failed
    runs-on: macos-latest
    if: ${{ success() || failure() }}
    continue-on-error: true
    steps:
      - run: echo "Done!"