name: moo
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  failed:
    runs-on: macos-latest
    steps:
      - run: exit 1
      - if: ${{ success() || failure() }}
        run: |
          mkdir -vp hello/
          echo "Hello World!" > greetings.txt
      # Instead of running `actions/cache@v3` directly, check it out locally.
      - name: Checkout actions/cache@v3
        if: ${{ success() || failure() }}
        uses: actions/checkout@v3
        with:
          repository: actions/cache
          ref: v3
          path: .tmp/actions/cache
      - name: Make actions/cache@v3 run always, not only when job succeeds
        if: ${{ success() || failure() }}
        # Tweak `action.yml` of `actions/cache@v3` to remove its `post-if`
        # condition, making it default to `post-if: always()`.
        run: |
          sed -i -e '/ post-if: /d' .tmp/actions/cache/action.yml
      - if: ${{ success() || failure() }}
        uses: ./.tmp/actions/cache
        id: cache
        with:
          path: hello
          key: hello-${{ github.job }}

  successful:
    needs: failed
    runs-on: macos-latest
    if: ${{ success() || failure() }}
    steps:
      - name: Checkout actions/cache@v3
        if: ${{ success() || failure() }}
        uses: actions/checkout@v3
        with:
          repository: actions/cache
          ref: v3
          path: .tmp/actions/cache
      - name: Make actions/cache@v3 run always, not only when job succeeds
        if: ${{ success() || failure() }}
        # Tweak `action.yml` of `actions/cache@v3` to remove its `post-if`
        # condition, making it default to `post-if: always()`.
        run: |
          sed -i -e '/ post-if: /d' .tmp/actions/cache/action.yml
      - if: ${{ success() || failure() }}
        uses: ./.tmp/actions/cache
        id: cache
        with:
          path: hello
          key: hello-failed
      - run: pwd && ls -alFh