name: moo
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  failed:
    runs-on: macos-latest
    steps:
      - run: exit 1
      - if: ${{ success() || failure() }}
        run: |
          mkdir -vp hello/
          echo "Hello World!" > greetings.txt
      - if: ${{ success() || failure() }}
        uses: martinheidegger/cache@always-save
        id: cache
        with:
          path: hello
          key: hello-${{ github.job }}

  successful:
    needs: failed
    runs-on: macos-latest
    if: ${{ success() || failure() }}
    steps:
      - run: echo "Done!"